services:
  postgres:
    image: postgres:18
    container_name: Auth-dotnet-DB 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${LOCAL_ROUTE_VOLUMES}/authapp-postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: unless-stopped
